
#Here is my page.

# Cannot change the following
#lsi: false
#safe: true
#source: [your repo's top level directory]
#incremental: false
#highlighter: rouge
#gist:
  #noscript: false
#kramdown:
  #math_engine: mathjax
  #syntax_highlighter: rouge
  
# Can change the following
#github: [metadata]
#encoding: UTF-8
 #kramdown:
   #input: GFM
   #hard_wrap: false
 #future: true
 #jailed: false
 #url: "https://danishnaseem05.github.io/"
 #baseurl: "Danish-Naseem/"
 #permalink: "/:about/"
 #permalink: "/:projects/"
 #permalink: "/:resume/"
 #gfm_quirks: paragraph_end

#title: Danish Naseem
#description: Portfolio
#theme: jekyll-theme-tactile
#permalink: /:categories/:title:output_ext

#plugins:
  #- jekyll-mentions
  #- jemoji
  #- jekyll-redirect-from
  #- jekyll-sitemap
  #- jekyll-feed
  #- jekyll-coffeescript
  #- jekyll-gist
  #- jekyll-github-metadata
  #- jekyll-paginate
  #- jekyll-relative-links
  #- jekyll-optional-front-matter
  #- jekyll-readme-index
  #- jekyll-default-layout
  #- jekyll-titles-from-headings
  #- jekyll-avatar
  #- jekyll-include-cache
  #- jekyll-seo-tag
